import type { GalleryItem, GalleryResponse } from "../types";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600000).toISOString();

const mockDeployments: GalleryItem[] = [
  {
    id: "d1",
    name: "marketing-site",
    title: "Marketing Dashboard",
    description: "Internal analytics dashboard for the marketing team with real-time metrics and campaign tracking.",
    subdomain: "marketing-site",
    framework: "nextjs",
    url: "https://marketing-site.example.com",
    createdAt: hoursAgo(48),
    ownerName: "alice",
    userId: "u1",
    accessMode: "public",
    accessUser: "",
    accessUsers: "",
    ttlHours: 0,
    expiresAt: "",
    mode: "deployment",
    networkQuota: "",
    locked: false,
    status: "running",
  },
  {
    id: "d2",
    name: "api-gateway",
    title: "API Gateway",
    description: "REST API gateway with rate limiting and authentication middleware.",
    subdomain: "api-gateway",
    framework: "go",
    url: "https://api-gateway.example.com",
    createdAt: hoursAgo(120),
    ownerName: "bob",
    userId: "u2",
    accessMode: "api_key",
    accessUser: "",
    accessUsers: "",
    ttlHours: 720,
    expiresAt: hoursFromNow(600),
    mode: "deployment",
    networkQuota: "5g",
    locked: true,
    status: "running",
  },
  {
    id: "d3",
    name: "ml-notebook",
    title: "ML Experiment Tracker",
    description: "Tracks machine learning experiments, model performance, and dataset versions.",
    subdomain: "ml-notebook",
    framework: "flask",
    url: "https://ml-notebook.example.com",
    createdAt: hoursAgo(6),
    ownerName: "alice",
    userId: "u1",
    accessMode: "basic_auth",
    accessUser: "admin",
    accessUsers: "",
    ttlHours: 168,
    expiresAt: hoursFromNow(162),
    mode: "deployment",
    networkQuota: "2g",
    locked: false,
    status: "running",
  },
  {
    id: "d4",
    name: "landing-page",
    title: "Product Landing",
    description: "Landing page for the new product launch with A/B testing variants.",
    subdomain: "landing-page",
    framework: "static",
    url: "https://landing-page.example.com",
    createdAt: hoursAgo(2),
    ownerName: "carol",
    userId: "u3",
    accessMode: "public",
    accessUser: "",
    accessUsers: "",
    ttlHours: 24,
    expiresAt: hoursFromNow(22),
    mode: "deployment",
    networkQuota: "",
    locked: false,
    status: "running",
  },
  {
    id: "d5",
    name: "chat-prototype",
    title: "Chat Prototype",
    description: "Real-time chat app prototype with WebSocket support.",
    subdomain: "chat-prototype",
    framework: "vite",
    url: "https://chat-prototype.example.com",
    createdAt: hoursAgo(1),
    ownerName: "bob",
    userId: "u2",
    accessMode: "public",
    accessUser: "",
    accessUsers: "",
    ttlHours: 0,
    expiresAt: "",
    mode: "sandbox",
    networkQuota: "",
    locked: false,
    status: "building",
  },
  {
    id: "d6",
    name: "data-pipeline",
    title: "Data Pipeline Monitor",
    description: "Monitors ETL pipeline health, data quality metrics, and processing latency.",
    subdomain: "data-pipeline",
    framework: "python",
    url: "https://data-pipeline.example.com",
    createdAt: hoursAgo(72),
    ownerName: "alice",
    userId: "u1",
    accessMode: "user",
    accessUser: "",
    accessUsers: "alice,bob",
    ttlHours: 0,
    expiresAt: "",
    mode: "deployment",
    networkQuota: "10g",
    locked: false,
    status: "failed",
  },
  {
    id: "d7",
    name: "docs-site",
    title: "Documentation",
    description: "Project documentation site with search and versioning.",
    subdomain: "docs-site",
    framework: "vite",
    url: "https://docs-site.example.com",
    createdAt: hoursAgo(240),
    ownerName: "carol",
    userId: "u3",
    accessMode: "public",
    accessUser: "",
    accessUsers: "",
    ttlHours: 0,
    expiresAt: "",
    mode: "deployment",
    networkQuota: "",
    locked: false,
    status: "stopped",
  },
  {
    id: "d8",
    name: "habit-tracker",
    title: "Habit Tracker",
    description: "Personal habit tracking app with streaks and daily reminders.",
    subdomain: "habit-tracker",
    framework: "react",
    url: "https://habit-tracker.example.com",
    createdAt: hoursAgo(12),
    ownerName: "bob",
    userId: "u2",
    accessMode: "public",
    accessUser: "",
    accessUsers: "",
    ttlHours: 72,
    expiresAt: hoursFromNow(60),
    mode: "deployment",
    networkQuota: "",
    locked: false,
    status: "running",
  },
];

export const mockGalleryResponse: GalleryResponse = {
  deployments: mockDeployments,
  userId: "u1",
  userRole: "admin",
  userName: "alice",
  hasPassword: true,
  serverVersion: "1.2.0",
};
