package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/AmirSoleimani/openberth/apps/server/internal/config"
)

type AccessControl struct {
	Mode      string // "public", "basic_auth", "api_key", "user"
	Username  string // for basic_auth
	Hash      string // bcrypt hash for basic_auth, plaintext key for api_key
	Subdomain string // for user mode: included in forward_auth URI
}

type ProxyManager struct {
	cfg *config.Config
}

func NewProxyManager(cfg *config.Config) *ProxyManager {
	return &ProxyManager{cfg: cfg}
}

func (p *ProxyManager) buildAuthBlock(ac *AccessControl) string {
	if ac == nil {
		return ""
	}
	switch ac.Mode {
	case "basic_auth":
		return fmt.Sprintf(`    basic_auth {
        %s %s
    }
`, ac.Username, ac.Hash)
	case "api_key":
		if ac.Hash == "" {
			return "" // no key stored — skip protection to avoid malformed Caddy config
		}
		return fmt.Sprintf(`    @unauthorized {
        not header X-Api-Key %s
    }
    respond @unauthorized "Unauthorized" 401
`, ac.Hash)
	case "user":
		return fmt.Sprintf(`    forward_auth localhost:%d {
        uri /internal/auth-check?subdomain=%s
        copy_headers X-OpenBerth-User
    }
`, p.cfg.Port, ac.Subdomain)
	}
	return ""
}

func (p *ProxyManager) buildSiteConfig(fqdn, authBlock, subdomain string, hostPort int) string {
	siteAddr := fqdn
	tlsDirective := ""
	if p.cfg.Insecure {
		siteAddr = "http://" + fqdn
	} else if p.cfg.CloudflareProxy {
		tlsDirective = "    tls internal\n"
	}
	return fmt.Sprintf(`# Auto-generated by OpenBerth
%s {
%s%s    log {
        output file %s {
            roll_size 50MiB
            roll_keep 3
            roll_keep_for 72h
        }
        format json
    }
    handle /_data/* {
        reverse_proxy localhost:%d
    }
    handle {
        reverse_proxy localhost:%d
        encode gzip
    }
    header {
        X-OpenBerth-Deploy %s
        -Server
        ?X-Content-Type-Options "nosniff"
        ?X-Frame-Options "SAMEORIGIN"
        ?Referrer-Policy "no-referrer"
    }
}
`, siteAddr, tlsDirective, authBlock, p.cfg.CaddyAccessLog, p.cfg.Port, hostPort, subdomain)
}

func (p *ProxyManager) AddRoute(subdomain string, hostPort int, ac *AccessControl) string {
	fqdn := subdomain + "." + p.cfg.Domain
	authBlock := p.buildAuthBlock(ac)
	siteConfig := p.buildSiteConfig(fqdn, authBlock, subdomain, hostPort)

	filePath := filepath.Join(p.cfg.CaddySitesDir, subdomain+".caddy")
	os.WriteFile(filePath, []byte(siteConfig), os.FileMode(p.cfg.ProxySiteConfigMode))
	p.reload()

	scheme := "https"
	if p.cfg.Insecure {
		scheme = "http"
	}
	return scheme + "://" + fqdn
}

func (p *ProxyManager) AddRouteNoReload(subdomain string, hostPort int, ac *AccessControl) {
	fqdn := subdomain + "." + p.cfg.Domain
	authBlock := p.buildAuthBlock(ac)
	siteConfig := p.buildSiteConfig(fqdn, authBlock, subdomain, hostPort)

	filePath := filepath.Join(p.cfg.CaddySitesDir, subdomain+".caddy")
	os.WriteFile(filePath, []byte(siteConfig), os.FileMode(p.cfg.ProxySiteConfigMode))
}

func (p *ProxyManager) RemoveRoute(subdomain string) {
	filePath := filepath.Join(p.cfg.CaddySitesDir, subdomain+".caddy")
	os.Remove(filePath)
	p.reload()
}

// Reload triggers Caddy to reload its configuration.
func (p *ProxyManager) Reload() {
	p.reload()
}

// ListCaddyFiles returns all .caddy filenames (without extension) in the sites directory.
func (p *ProxyManager) ListCaddyFiles() []string {
	entries, err := os.ReadDir(p.cfg.CaddySitesDir)
	if err != nil {
		return nil
	}
	var names []string
	for _, e := range entries {
		if !e.IsDir() && filepath.Ext(e.Name()) == ".caddy" {
			names = append(names, strings.TrimSuffix(e.Name(), ".caddy"))
		}
	}
	return names
}

// BlockRouteNoReload overwrites a site's Caddy config to serve 503 (quota exceeded)
// while keeping /_data/* functional. Does not trigger a Caddy reload.
func (p *ProxyManager) BlockRouteNoReload(subdomain string) {
	fqdn := subdomain + "." + p.cfg.Domain
	siteAddr := fqdn
	tlsDirective := ""
	if p.cfg.Insecure {
		siteAddr = "http://" + fqdn
	} else if p.cfg.CloudflareProxy {
		tlsDirective = "    tls internal\n"
	}
	siteConfig := fmt.Sprintf(`# Auto-generated by OpenBerth (BLOCKED — bandwidth quota exceeded)
%s {
%s    log {
        output file %s {
            roll_size 50MiB
            roll_keep 3
            roll_keep_for 72h
        }
        format json
    }
    handle /_data/* {
        reverse_proxy localhost:%d
    }
    respond "Bandwidth quota exceeded" 503
}
`, siteAddr, tlsDirective, p.cfg.CaddyAccessLog, p.cfg.Port)

	filePath := filepath.Join(p.cfg.CaddySitesDir, subdomain+".caddy")
	os.WriteFile(filePath, []byte(siteConfig), os.FileMode(p.cfg.ProxySiteConfigMode))
}

// NormalizeSiteFileModes chmods every existing .caddy file under CaddySitesDir
// to the configured ProxySiteConfigMode. Called once at startup so that files
// written by prior releases (with world-readable 0644) are tightened in place
// without waiting for a deploy/update cycle to rewrite them.
func (p *ProxyManager) NormalizeSiteFileModes() {
	entries, err := os.ReadDir(p.cfg.CaddySitesDir)
	if err != nil {
		return
	}
	mode := os.FileMode(p.cfg.ProxySiteConfigMode)
	for _, e := range entries {
		if e.IsDir() || filepath.Ext(e.Name()) != ".caddy" {
			continue
		}
		os.Chmod(filepath.Join(p.cfg.CaddySitesDir, e.Name()), mode)
	}
}

// RemoveAllRoutes removes all .caddy files from the sites directory and reloads Caddy.
// Used before restore to clean slate.
func (p *ProxyManager) RemoveAllRoutes() {
	entries, err := os.ReadDir(p.cfg.CaddySitesDir)
	if err != nil {
		return
	}
	for _, e := range entries {
		if !e.IsDir() && filepath.Ext(e.Name()) == ".caddy" {
			os.Remove(filepath.Join(p.cfg.CaddySitesDir, e.Name()))
		}
	}
	p.reload()
}

// RemoveRouteNoReload removes a Caddy config file without triggering a reload.
func (p *ProxyManager) RemoveRouteNoReload(subdomain string) {
	filePath := filepath.Join(p.cfg.CaddySitesDir, subdomain+".caddy")
	os.Remove(filePath)
}

func (p *ProxyManager) reload() {
	if err := exec.Command("systemctl", "reload", "caddy").Run(); err != nil {
		exec.Command("caddy", "reload", "--config", "/etc/caddy/Caddyfile").Run()
	}
}
